language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-hubot-bot' ]; then cd .. && eval "mv $currentfolder generator-hubot-bot" && cd generator-hubot-bot; fi

